name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'  # Change this to use .NET 8.0

      - name: Restore NuGet Packages
        run: dotnet restore

      - name: Build the Project
        run: dotnet build --configuration Release

      - name: Publish the Project
        run: dotnet publish -c Release -o publish

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-published-artifact
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: my-published-artifact

      - name: Deploy to IIS
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'your-iis-app-name'
          publish-profile: ${{ secrets.IIS_PUBLISH_PROFILE }}
          package: './path-to-downloaded-artifact'
