name: Build and Deploy to IIS on Azure VM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'  # Adjust for your app's version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release

    - name: Publish the application
      run: dotnet publish --configuration Release --output ./published

    - name: Archive the published application
      run: |
        Compress-Archive -Path ./published/* -DestinationPath ./artifact.zip

    - name: Upload artifact for deployment
      uses: actions/upload-artifact@v3
      with:
        name: my-app-artifact
        path: ./artifact.zip

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: my-app-artifact
        path: ./my-app-artifact

    - name: Install Web Deploy
      run: choco install webdeploy

    - name: Deploy to IIS on Azure VM
      shell: pwsh
      run: |
        $msdeployPath = "C:\Program Files (x86)\IIS\Microsoft Web Deploy V3\msdeploy.exe"
        $artifactPath = "$env:GITHUB_WORKSPACE\my-app-artifact\artifact.zip"

        $username = "${{ secrets.AZURE_IIS_USERNAME }}"
        $password = "${{ secrets.AZURE_IIS_PASSWORD }}"
        
        # Write-Output "Checking for msdeploy.exe at $msdeployPath"
        # Write-Output "Checking for artifact at $artifactPath"
        Write-Output "Username: $username"
        Write-Output "Artifact Path: $artifactPath"

        if (Test-Path $msdeployPath) {
          if (Test-Path $artifactPath) {
            & $msdeployPath `
              -verb:sync `
              -source:package=$artifactPath `
              -dest:auto,computerName=https://20.5.240.49:8172/msdeploy.axd,username=$username,password=$password,authType=Basic `
              -allowUntrusted `
              -verbose
          } else {
            Write-Error "Artifact not found at $artifactPath. Please check the download path and verify the artifact name."
          }
        } else {
          Write-Error "msdeploy.exe not found at $msdeployPath"
        }
