name: .NET CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    env:
      DOTNET_CLI_HOME: "C:\\Program Files\\dotnet"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test --no-restore --configuration Release

      - name: Publish application
        run: dotnet publish --no-restore --configuration Release --output ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    if: success()
    steps:
      - name: Deploy to Server
        uses: azure/powershell@v1
        with:
          azPSVersion: 'latest'
          inlineScript: |
            # Create credentials using GitHub secrets
            $credentials = New-Object System.Management.Automation.PSCredential("${{ secrets.IIS_USERNAME }}", (ConvertTo-SecureString "${{ secrets.IIS_PASSWORD }}" -AsPlainText -Force))
            
            # Map network drive
            New-PSDrive -Name Y -PSProvider FileSystem -Root "\\new-vm\coreapp" -Persist -Credential $credentials
            
            # Copy files to the network drive
            Copy-Item -Path './publish/*' -Destination 'Y:\' -Force
            
            # Remove network drive
            Remove-PSDrive -Name Y

      - name: Notification
        run: echo 'Deployment successful!'
