name: .NET CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test --no-restore --configuration Release

      - name: Publish application
        run: dotnet publish --no-restore --configuration Release --output ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    if: success()
    steps:
      - name: Deploy to Server
        uses: azure/powershell@v1
        with:
          azPSVersion: 'latest'
          inlineScript: |
            # Define the destination path on the remote server
            $destinationPath = "C:\inetpub\wwwroot\coreapp" # Adjust as needed for your IIS application directory

            # Define the username and password
            $username = "${{ secrets.IIS_USERNAME }}" # GitHub secret for the username
            $password = "${{ secrets.IIS_PASSWORD }}" # GitHub secret for the password
            
            # Convert the password to a secure string
            $securePassword = ConvertTo-SecureString $password -AsPlainText -Force

            # Create a credential object
            $credentials = New-Object System.Management.Automation.PSCredential($username, $securePassword)

            # Create a session to the remote machine
            $session = New-PSSession -ComputerName "20.5.240.49" -Credential $credentials -UseSSL

            # Define the path to the published files
            $sourcePath = "${{ github.workspace }}\publish\*"

            # Copy files to the remote destination path
            Copy-Item -Path $sourcePath -Destination $destinationPath -Recurse -Force -ToSession $session

            # Remove the session
            Remove-PSSession -Session $session

      - name: Notification
        run: echo 'Deployment successful!'
