name: .NET CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test --no-restore --configuration Release

      - name: Publish application
        run: dotnet publish --no-restore --configuration Release --output ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    if: success()
    steps:
      - name: Deploy to Server
        uses: azure/powershell@v1
        with:
          azPSVersion: 'latest'
          inlineScript: |
            # Define the network path and credentials
            $networkPath = "\\new-vm\coreapp"
            $username = "${{ secrets.IIS_USERNAME }}" # GitHub secret for the username
            $password = "${{ secrets.IIS_PASSWORD }}" # GitHub secret for the password
            
            # Create a secure string for the password
            $securePassword = ConvertTo-SecureString $password -AsPlainText -Force

            # Create a PSCredential object
            $credentials = New-Object System.Management.Automation.PSCredential($username, $securePassword)

            # Map the network drive
            New-PSDrive -Name Y -PSProvider FileSystem -Root $networkPath -Persist -Credential $credentials

            # Copy files to the network drive
            Copy-Item -Path './publish/*' -Destination 'Y:\' -Force
            
            # Remove network drive
            Remove-PSDrive -Name Y

      - name: Notification
        run: echo 'Deployment successful!'
