name: CI/CD Pipeline for IIS

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'  # Specify your .NET version

      - name: Restore NuGet Packages
        run: dotnet restore

      - name: Build the Project
        run: dotnet build --configuration Release

      - name: Publish the Project
        run: dotnet publish -c Release -o publish

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: published-artifact
          path: publish  # Upload the publish directory as an artifact

  deploy:
    runs-on: windows-latest
    needs: build  # This job will only run after the build job completes successfully

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: published-artifact

      - name: Deploy to IIS
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Test'  # Name of your IIS application
          publish-profile: ${{ secrets.IIS_PUBLISH_PROFILE }}  # Use a GitHub secret for secure credentials
          package: ./publish  # Path to the downloaded published output
