name: .NET CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    env:
      DOTNET_CLI_HOME: "C:\\Program Files\\dotnet"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Publish application
        run: dotnet publish --no-restore --configuration Release --output ./publish
  

      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test --no-restore --configuration Release

      - name: Publish application
        run: dotnet publish --no-restore --configuration Release --output ./publish

      - name: Deploy to Server
        uses: azure/powershell@v1
        with:
          azPSVersion: 'latest'
          inlineScript: |
            Test-NetConnection -ComputerName 10.0.1.4 -Port 445
            $credentials = New-Object System.Management.Automation.PSCredential("sahil", (ConvertTo-SecureString "Sahil1234567" -AsPlainText -Force))
            # Use the correct network path for the shared folder
            New-PSDrive -Name Y -PSProvider FileSystem -Root "\\new-vm\coreapp" -Persist -Credential $credentials
            Copy-Item -Path './publish/*' -Destination 'Y:\' -Force
            Remove-PSDrive -Name Y
        env:
          IIS_USERNAME: sahil
          IIS_PASSWORD: Sahil1234567

  post-build:
    runs-on: windows-latest
    needs: build
    if: success()
    steps:
      - name: Notification
        run: echo 'Build, test, and publish successful!'
